"""Sphinx configuration."""
project = "My Data Model"
author = "Gareth Stockwell"
copyright = "2023, Gareth Stockwell"
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx_click",
    "myst_parser",
]
autodoc_class_signature = "separated"
autodoc_typehints = "description"
autosummary_generate = True
html_theme = "furo"
templates_path = ["_templates"]


def _skip_member_attrs_dunder(app, what, name, obj, skip, options):  # type: ignore
    if getattr(obj, "__module__", None) == "pydantic._internal._dataclasses":
        return True

    if obj.__doc__ is not None and "generated by attrs" in obj.__doc__:
        return True


def setup(app):  # type: ignore
    """Set up Sphinx."""
    app.connect("autodoc-skip-member", _skip_member_attrs_dunder)
